name: CI
on: [push, pull_request]

jobs:
  freebsd-test:
    runs-on: ${{ matrix.os.host }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.3'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run CI script on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.29.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            sudo pkg install -y \
              devel/py-copier \
              devel/py-pre-commit \
              devel/py-pyright \
              devel/py-ruff \
              devel/py-tox \
              git \
              node24 \
              uv \
              ;

            export PATH="$HOME"/.local/bin:"$PATH"
            uv self version
            uv tool install poethepoet

            uv run test.py

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]

    steps:
      - name: 'Disable `autocrlf` in Git'
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.9.0'

      - name: Install dependencies
        run: |
          uv tool install copier
          uv tool install poethepoet
          uv tool install pre-commit
          uv tool install tox --with tox-uv

      - name: Test
        run: |
          uv run test.py
